#!/bin/bash
if [ $# -ne 1 ];then 
	echo "Usage: index on|off"
else
	docker exec ft_server bash -c \
	"sed -Ei 's/autoindex (on|off)/autoindex $1/' /etc/nginx/sites-available/default;\
		nginx -s reload;"
fi
