#!/bin/bash
if [ $# -eq 1 ] && [[ "$1" == 'on' || "$1" == 'off' ]];then
	docker exec nginx bash -c \
	"sed -Ei 's/autoindex (on|off)/autoindex $1/' /etc/nginx/sites-available/default;\
		nginx -s reload;"
else
	echo "Usage: index on|off"
fi
